CREATE TABLE blogs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  author VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  heading VARCHAR(255) NOT NULL,
  date DATETIME DEFAULT CURRENT_TIMESTAMP
);
